// Un alert() espone 5 numeri generati casualmente.
// Da li parte un timer di 30 secondi.
// Dopo 30 secondi l'utente deve inserire, uno alla volta, i numeri che ha visto precedentemente, tramite il prompt().
// Dopo che sono stati inseriti i 5 numeri, il software dice quanti e quali dei numeri da indovinare sono stati individuati.



// Asking the user how many numbers he/she is willing to try to remember.
let numbersToBeGenerated = parseInt(prompt("Choose how many numbers would you like to be generated by the computer:"))

// Saving the chosen numbers into a variable.
let selectedNumbers = randomNumberGenerator(numbersToBeGenerated, 1, 100)
alert(selectedNumbers);








// FUNCTIONS

// Function needed to generate and show the user some random numbers within a fixed interval, given his input.
function randomNumberGenerator(num, min, max) {
    let generatedArray = [];
    let i=0;
    while (i < num) {
        let generatedNumber = (Math.floor(Math.random() * (max - min + 1)) + min);
        if (!(generatedArray.includes(generatedNumber))) {
            generatedArray.push(generatedNumber);
            i++
        }
        
    }
    return generatedArray;
} 


 
